#!/bin/bash

# Name of the application
NAME="django_palette"
# Base directory for project
BASE_DIRECTORY=$PWD
# Django project directory
GUNICORN_BIN=$PWD/.venv/bin/gunicorn
# Django project directory
DJANGODIR=$PWD/sandbox
# we will communicte using this unix socket
SOCKFILE=$PWD/run/gunicorn.sock
# the user to run as (use username from current session)
USER=$USER
# the group to run as (assume it is the same name as username)
GROUP=$USER
# how many worker processes should Gunicorn spawn
NUM_WORKERS=3
# which settings file should Django use
DJANGO_SETTINGS_MODULE=sandbox.settings.demo
# WSGI module name
DJANGO_WSGI_MODULE=sandbox.wsgi

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR
source ../bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn

# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec $GUNICORN_BIN ${DJANGO_WSGI_MODULE}:application \
--name $NAME \
--workers $NUM_WORKERS \
--user=$USER --group=$GROUP \
--bind=unix:$SOCKFILE \
--log-level=debug \
--log-file=-
